export const cards = [
    {
    id: 1,
    picture: "Card 1",
    title: "Card 1",
    liveButton: true,
    gitButton: false,
    },
    {
    id: 2,
    picture: "Card 2",
    title: "Card 2",
    liveButton: false,
    gitButton: true,
    },
    {
    id: 3,
    picture: "Card 3",
    title: "Card 3",
    liveButton: true,
    gitButton: true,
    },
    {
    id: 4,
    picture: "Card 4",
    title: "Card 4",
    liveButton: true,
    gitButton: false,
    },
    {
    id: 5,
    picture: "Card 5",
    title: "Card 5",
    liveButton: false,
    gitButton: false,
    },
    {
    id: 6,
    picture: "Card 6",
    title: "Card 6",
    liveButton: true,
    gitButton: false,
    },
    {
    id: 7,
    picture: "Card 7",
    title: "Card 7",
    liveButton: false,
    gitButton: true,
    },
];